import 'backend_strings.dart';
import 'strings.dart';

class CivicStrings {
  final String language;
  const CivicStrings(this.language);
  String t(String key) =>
      (language == 'kk' ? kk : ru)[key] ??
      (BackendStrings.ru.containsKey(key)
          ? BackendStrings(language).t(key)
          : Strings(language).t(key));
  static const ru = {
    'server': 'Сервер',
    'more': 'Показать ещё',
    'empty': 'Здесь пока ничего нет',
    'allStates': 'Все статусы',
    'openState': 'Открытые',
    'resolvedState': 'Решённые',
    'allCategories': 'Все категории',
    'city': 'Город',
    'search': 'Поиск проблем',
    'loginRequired': 'Войдите, чтобы продолжить',
    'join': 'У меня тоже',
    'joined': 'Вы присоединились',
    'history': 'История',
    'descriptionStep': 'Описание',
    'placeStep': 'Место',
    'reviewStep': 'Проверка',
    'titleField': 'Заголовок (необязательно)',
    'descriptionField': 'Описание, 10–2000 символов',
    'addressField': 'Адрес или ориентир',
    'categoryField': 'Категория',
    'publication': 'Согласен на публикацию обращения после модерации',
    'pendingNote':
        'До модерации обращение увидят только вы и уполномоченные сотрудники.',
    'draftSaved': 'Черновик сохраняется на этом устройстве',
    'draftSaveError':
        'Не удалось сохранить черновик. Не закрывайте форму, пока не повторите сохранение.',
    'checkSubmission': 'Проверить результат отправки',
    'uncertain':
        'Результат отправки пока неизвестен. Сначала проверим сервер. Поля заблокированы, чтобы сохранить исходный запрос.',
    'received': 'Принято приложением',
    'continue': 'Продолжить',
    'send': 'Отправить обращение',
    'validation': 'Проверьте категорию, описание, точку и согласие.',
    'resume': 'Продолжить черновик',
    'newReport': 'Сообщить о проблеме',
    'saveDraft': 'Сохранить черновик и выйти',
    'discardDraft': 'Удалить черновик',
    'leaveForm': 'Выйти из формы?',
    'keepEditing': 'Продолжить заполнение',
    'private': 'Только для вас',
    'supports': 'Присоединились',
    'notifications': 'Уведомления',
    'alerts': 'Предупреждения',
    'houses': 'Мои дома',
    'subscription': 'Подписка на обновления',
    'confirmResult': 'Подтвердить результат',
    'stillPresent': 'Проблема осталась',
    'flag': 'Пожаловаться на публикацию',
    'explanation': 'Пояснение',
    'clarify': 'Ответить на уточнение',
    'withdraw': 'Отозвать обращение',
    'withdrawBody': 'Отозвать это обращение?',
    'noMapData': 'Нет проблем в этой области',
    'geoSearch': 'Найти адрес',
    'similar': 'Похожие проблемы',
    'date': 'Дата',
    'serverNotice':
        'Обращения поступают на сервер. До публикации они доступны только автору и уполномоченным сотрудникам.',
  };
  static const kk = {
    'server': 'Сервер',
    'more': 'Тағы көрсету',
    'empty': 'Мұнда әзірге ештеңе жоқ',
    'allStates': 'Барлық күйлер',
    'openState': 'Ашық',
    'resolvedState': 'Шешілген',
    'allCategories': 'Барлық санаттар',
    'city': 'Қала',
    'search': 'Мәселелерді іздеу',
    'loginRequired': 'Жалғастыру үшін кіріңіз',
    'join': 'Менде де бар',
    'joined': 'Сіз қосылдыңыз',
    'history': 'Тарих',
    'descriptionStep': 'Сипаттама',
    'placeStep': 'Орын',
    'reviewStep': 'Тексеру',
    'titleField': 'Тақырып (міндетті емес)',
    'descriptionField': 'Сипаттама, 10–2000 таңба',
    'addressField': 'Мекенжай немесе бағдар',
    'categoryField': 'Санат',
    'publication': 'Модерациядан кейін өтінішті жариялауға келісемін',
    'pendingNote':
        'Модерацияға дейін өтінішті тек сіз және уәкілетті қызметкерлер көреді.',
    'draftSaved': 'Нобай осы құрылғыда сақталады',
    'draftSaveError': 'Нобай сақталмады. Қайта сақтамайынша форманы жаппаңыз.',
    'checkSubmission': 'Жіберу нәтижесін тексеру',
    'uncertain':
        'Жіберу нәтижесі белгісіз. Алдымен серверді тексереміз. Бастапқы сұрауды сақтау үшін өрістер бұғатталған.',
    'received': 'Қолданба қабылдады',
    'continue': 'Жалғастыру',
    'send': 'Өтініш жіберу',
    'validation': 'Санатты, сипаттаманы, нүктені және келісімді тексеріңіз.',
    'resume': 'Нобайды жалғастыру',
    'newReport': 'Мәселе туралы хабарлау',
    'saveDraft': 'Нобайды сақтап шығу',
    'discardDraft': 'Нобайды жою',
    'leaveForm': 'Формадан шығу керек пе?',
    'keepEditing': 'Толтыруды жалғастыру',
    'private': 'Тек сізге',
    'supports': 'Қосылғандар',
    'notifications': 'Хабарламалар',
    'alerts': 'Ескертулер',
    'houses': 'Менің үйлерім',
    'subscription': 'Жаңартуларға жазылу',
    'confirmResult': 'Нәтижені растау',
    'stillPresent': 'Мәселе сақталды',
    'flag': 'Жарияланымға шағымдану',
    'explanation': 'Түсініктеме',
    'clarify': 'Нақтылауға жауап беру',
    'withdraw': 'Өтінішті қайтарып алу',
    'withdrawBody': 'Осы өтінішті қайтарып алу керек пе?',
    'noMapData': 'Бұл аумақта мәселе жоқ',
    'geoSearch': 'Мекенжай табу',
    'similar': 'Ұқсас мәселелер',
    'date': 'Күні',
    'serverNotice':
        'Өтініштер серверге жіберіледі. Жарияланғанға дейін оларды тек автор мен уәкілетті қызметкерлер көреді.',
  };
}
