"""Generate the complete runtime contract from the checked-in OpenAPI snapshot."""
import json
from pathlib import Path
schema = json.loads(Path('docs/openapi.json').read_text())
operations = []
for path, item in schema['paths'].items():
    for method, op in item.items():
        if method not in ('get', 'post', 'put', 'patch', 'delete'):
            continue
        content = op.get('requestBody', {}).get('content', {})
        responses = op['responses']
        success = next((v for k, v in responses.items() if k.startswith('2') and v.get('content')), {})
        operations.append(dict(id=op['operationId'], method=method.upper(), path=path,
            title=op.get('summary', ''), description=op.get('description', ''),
            tags=op.get('tags', []), authenticated=bool(op.get('security')),
            parameters=op.get('parameters', []), body=next(iter(content.values()), {}).get('schema'),
            multipart='multipart/form-data' in content,
            response=success.get('content', {}).get('application/json', {}).get('schema'),
            statuses=[int(k) for k in responses if k.startswith('2')]))
# JSON in a raw Dart string keeps regular expressions and Unicode unmodified.
data = json.dumps(dict(version=schema['info']['version'], operations=operations,
    schemas=schema['components']['schemas']), ensure_ascii=False, separators=(',', ':'))
assert "'''" not in data
Path('lib/api_contract.g.dart').write_text("// Generated by tool/generate_contract.py. Do not edit.\nimport 'dart:convert';\n\nfinal Map<String, dynamic> generatedContract = jsonDecode(r'''" + data + "''') as Map<String, dynamic>;\n")

# Keep the generated artifact deterministic under the repository formatter.
import subprocess
subprocess.run(["dart", "format", "lib/api_contract.g.dart"], check=True)
